package com.daogenerator;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.daogenerator.lightBulbTable;
import com.daogenerator.effectTable;
import com.daogenerator.sensorTable;
import com.daogenerator.roomTable;

import com.daogenerator.lightBulbTableDao;
import com.daogenerator.effectTableDao;
import com.daogenerator.sensorTableDao;
import com.daogenerator.roomTableDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig lightBulbTableDaoConfig;
    private final DaoConfig effectTableDaoConfig;
    private final DaoConfig sensorTableDaoConfig;
    private final DaoConfig roomTableDaoConfig;

    private final lightBulbTableDao lightBulbTableDao;
    private final effectTableDao effectTableDao;
    private final sensorTableDao sensorTableDao;
    private final roomTableDao roomTableDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        lightBulbTableDaoConfig = daoConfigMap.get(lightBulbTableDao.class).clone();
        lightBulbTableDaoConfig.initIdentityScope(type);

        effectTableDaoConfig = daoConfigMap.get(effectTableDao.class).clone();
        effectTableDaoConfig.initIdentityScope(type);

        sensorTableDaoConfig = daoConfigMap.get(sensorTableDao.class).clone();
        sensorTableDaoConfig.initIdentityScope(type);

        roomTableDaoConfig = daoConfigMap.get(roomTableDao.class).clone();
        roomTableDaoConfig.initIdentityScope(type);

        lightBulbTableDao = new lightBulbTableDao(lightBulbTableDaoConfig, this);
        effectTableDao = new effectTableDao(effectTableDaoConfig, this);
        sensorTableDao = new sensorTableDao(sensorTableDaoConfig, this);
        roomTableDao = new roomTableDao(roomTableDaoConfig, this);

        registerDao(lightBulbTable.class, lightBulbTableDao);
        registerDao(effectTable.class, effectTableDao);
        registerDao(sensorTable.class, sensorTableDao);
        registerDao(roomTable.class, roomTableDao);
    }
    
    public void clear() {
        lightBulbTableDaoConfig.getIdentityScope().clear();
        effectTableDaoConfig.getIdentityScope().clear();
        sensorTableDaoConfig.getIdentityScope().clear();
        roomTableDaoConfig.getIdentityScope().clear();
    }

    public lightBulbTableDao getLightBulbTableDao() {
        return lightBulbTableDao;
    }

    public effectTableDao getEffectTableDao() {
        return effectTableDao;
    }

    public sensorTableDao getSensorTableDao() {
        return sensorTableDao;
    }

    public roomTableDao getRoomTableDao() {
        return roomTableDao;
    }

}
