package com.daogenerator;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table EFFECT_TABLE.
 */
public class effectTable {

    private Long id;
    private String name;
    private Long intensity;
    private Long dutyCycle;
    private Long color1;
    private Long color2;
    private Long color3;

    public effectTable() {
    }

    public effectTable(Long id) {
        this.id = id;
    }

    public effectTable(Long id, String name, Long intensity, Long dutyCycle, Long color1, Long color2, Long color3) {
        this.id = id;
        this.name = name;
        this.intensity = intensity;
        this.dutyCycle = dutyCycle;
        this.color1 = color1;
        this.color2 = color2;
        this.color3 = color3;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Long getIntensity() {
        return intensity;
    }

    public void setIntensity(Long intensity) {
        this.intensity = intensity;
    }

    public Long getDutyCycle() {
        return dutyCycle;
    }

    public void setDutyCycle(Long dutyCycle) {
        this.dutyCycle = dutyCycle;
    }

    public Long getColor1() {
        return color1;
    }

    public void setColor1(Long color1) {
        this.color1 = color1;
    }

    public Long getColor2() {
        return color2;
    }

    public void setColor2(Long color2) {
        this.color2 = color2;
    }

    public Long getColor3() {
        return color3;
    }

    public void setColor3(Long color3) {
        this.color3 = color3;
    }

}
