package com.daogenerator;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table LIGHT_BULB_TABLE.
 */
public class lightBulbTable {

    private Long id;
    private String name;
    private Long effectId;

    public lightBulbTable() {
    }

    public lightBulbTable(Long id) {
        this.id = id;
    }

    public lightBulbTable(Long id, String name, Long effectId) {
        this.id = id;
        this.name = name;
        this.effectId = effectId;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Long getEffectId() {
        return effectId;
    }

    public void setEffectId(Long effectId) {
        this.effectId = effectId;
    }

}
