package com.daogenerator;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table ROOM_TABLE.
 */
public class roomTable {

    private Long id;
    private Long lightBulbId;

    public roomTable() {
    }

    public roomTable(Long id) {
        this.id = id;
    }

    public roomTable(Long id, Long lightBulbId) {
        this.id = id;
        this.lightBulbId = lightBulbId;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getLightBulbId() {
        return lightBulbId;
    }

    public void setLightBulbId(Long lightBulbId) {
        this.lightBulbId = lightBulbId;
    }

}
