//package com.lit.daogenerator;
//
//// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.
///**
// * Entity mapped to table BRIDGE_INFO.
// */
//public class BridgeInfo {
//
//    private Long id;
//    private String inherited_name;
//    private String provided_name;
//    private String room_location;
//
//    public BridgeInfo() {
//    }
//
//    public BridgeInfo(Long id) {
//        this.id = id;
//    }
//
//    public BridgeInfo(Long id, String inherited_name, String provided_name, String room_location) {
//        this.id = id;
//        this.inherited_name = inherited_name;
//        this.provided_name = provided_name;
//        this.room_location = room_location;
//    }
//
//    public Long getId() {
//        return id;
//    }
//
//    public void setId(Long id) {
//        this.id = id;
//    }
//
//    public String getInherited_name() {
//        return inherited_name;
//    }
//
//    public void setInherited_name(String inherited_name) {
//        this.inherited_name = inherited_name;
//    }
//
//    public String getProvided_name() {
//        return provided_name;
//    }
//
//    public void setProvided_name(String provided_name) {
//        this.provided_name = provided_name;
//    }
//
//    public String getRoom_location() {
//        return room_location;
//    }
//
//    public void setRoom_location(String room_location) {
//        this.room_location = room_location;
//    }
//
//}
