package com.lit.daogenerator;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.lit.daogenerator.RoomTable;
import com.lit.daogenerator.LightTable;

import com.lit.daogenerator.RoomTableDao;
import com.lit.daogenerator.LightTableDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig roomTableDaoConfig;
    private final DaoConfig lightTableDaoConfig;

    private final RoomTableDao roomTableDao;
    private final LightTableDao lightTableDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        roomTableDaoConfig = daoConfigMap.get(RoomTableDao.class).clone();
        roomTableDaoConfig.initIdentityScope(type);

        lightTableDaoConfig = daoConfigMap.get(LightTableDao.class).clone();
        lightTableDaoConfig.initIdentityScope(type);

        roomTableDao = new RoomTableDao(roomTableDaoConfig, this);
        lightTableDao = new LightTableDao(lightTableDaoConfig, this);

        registerDao(RoomTable.class, roomTableDao);
        registerDao(LightTable.class, lightTableDao);
    }
    
    public void clear() {
        roomTableDaoConfig.getIdentityScope().clear();
        lightTableDaoConfig.getIdentityScope().clear();
    }

    public RoomTableDao getRoomTableDao() {
        return roomTableDao;
    }

    public LightTableDao getLightTableDao() {
        return lightTableDao;
    }

}
