package com.lit.daogenerator;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table LIGHT_TABLE.
 */
public class LightTable {

    private Long id;
    private String name;
    private Integer red;
    private Integer green;
    private Integer blue;
    private Long roomId;
    private String hueId;
    private Boolean effectOn;

    public LightTable() {
    }

    public LightTable(Long id) {
        this.id = id;
    }

    public LightTable(Long id, String name, Integer red, Integer green, Integer blue, Long roomId, String hueId, Boolean effectOn) {
        this.id = id;
        this.name = name;
        this.red = red;
        this.green = green;
        this.blue = blue;
        this.roomId = roomId;
        this.hueId = hueId;
        this.effectOn = effectOn;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Integer getRed() {
        return red;
    }

    public void setRed(Integer red) {
        this.red = red;
    }

    public Integer getGreen() {
        return green;
    }

    public void setGreen(Integer green) {
        this.green = green;
    }

    public Integer getBlue() {
        return blue;
    }

    public void setBlue(Integer blue) {
        this.blue = blue;
    }

    public Long getRoomId() {
        return roomId;
    }

    public void setRoomId(Long roomId) {
        this.roomId = roomId;
    }

    public String getHueId() {
        return hueId;
    }

    public void setHueId(String hueId) {
        this.hueId = hueId;
    }

    public Boolean getEffectOn() {
        return effectOn;
    }

    public void setEffectOn(Boolean effectOn) {
        this.effectOn = effectOn;
    }

}
