package com.lit.daogenerator;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import com.lit.daogenerator.PowerSavePreference;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table POWER_SAVE_PREFERENCE.
*/
public class PowerSavePreferenceDao extends AbstractDao<PowerSavePreference, Long> {

    public static final String TABLENAME = "POWER_SAVE_PREFERENCE";

    /**
     * Properties of entity PowerSavePreference.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Min = new Property(1, Integer.class, "min", false, "MIN");
        public final static Property Max = new Property(2, Integer.class, "max", false, "MAX");
    };


    public PowerSavePreferenceDao(DaoConfig config) {
        super(config);
    }
    
    public PowerSavePreferenceDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'POWER_SAVE_PREFERENCE' (" + //
                "'_id' INTEGER PRIMARY KEY ," + // 0: id
                "'MIN' INTEGER," + // 1: min
                "'MAX' INTEGER);"); // 2: max
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'POWER_SAVE_PREFERENCE'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, PowerSavePreference entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Integer min = entity.getMin();
        if (min != null) {
            stmt.bindLong(2, min);
        }
 
        Integer max = entity.getMax();
        if (max != null) {
            stmt.bindLong(3, max);
        }
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public PowerSavePreference readEntity(Cursor cursor, int offset) {
        PowerSavePreference entity = new PowerSavePreference( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getInt(offset + 1), // min
            cursor.isNull(offset + 2) ? null : cursor.getInt(offset + 2) // max
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, PowerSavePreference entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setMin(cursor.isNull(offset + 1) ? null : cursor.getInt(offset + 1));
        entity.setMax(cursor.isNull(offset + 2) ? null : cursor.getInt(offset + 2));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(PowerSavePreference entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(PowerSavePreference entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
