package com.lit.daogenerator;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table POWER_SAVE_PREFERENCE.
 */
public class PowerSavePreference {

    private Long id;
    private Integer min;
    private Integer max;

    public PowerSavePreference() {
    }

    public PowerSavePreference(Long id) {
        this.id = id;
    }

    public PowerSavePreference(Long id, Integer min, Integer max) {
        this.id = id;
        this.min = min;
        this.max = max;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getMin() {
        return min;
    }

    public void setMin(Integer min) {
        this.min = min;
    }

    public Integer getMax() {
        return max;
    }

    public void setMax(Integer max) {
        this.max = max;
    }

}
